package com.example.smkitdemoapp.models

enum class DemoExercise(var count: Int = 0) {
    Highlight,
    Background,
    AlternateWindmillToeTouch,
    Burpees,
    Crunches,
    Froggers,
    GlutesBridge,
    HighKnees,
    JumpingJacks,
    Jumps,
    LateralRaises,
    Lunge,
    LungeSide,
    PlankHighKneeToElbow,
    PlankHighShoulderTaps,
    PlankMountainClimber,
    PushupRegular,
    ReverseSitToTableTop,
    SquatRegular,
    SquatSumo,
    StandingStepReverseAirFly,
    ShouldersPress,
    SideStepJacks,
    SkaterHops,
    StandingAlternateToeTouch,
    StandingBicycleCrunches,
    StandingObliqueCrunches,
    SkiJumps,
    BearStatic,
    HandStand,
    LungeRegularStatic,
    PlankHighStatic,
    PlankLowStatic,
    PlankSideLowStatic,
    SitupRussianTwistStatic,
    SquatRegularOverheadStatic,
    SquatRegularStatic,
    SquatSumoStatic,
    TuckHold,
    StandingSideBendRight,
    StandingSideBendLeft,
    StandingKneeRaiseRight,
    StandingKneeRaiseLeft,
    JeffersonCurl,
    JeffersonCurlRight,
    LungeSideStaticRight,
    LungeSideStaticLeft,
    AnklesMobility,
    AnkleMobilityLeft,
    AnkleMobilityRight,
    HamstringMobility,
    InnerThighMobility,
    HipExternalRotationGlutesMobility,
    HipInternalRotationMobility,
    HipFlexionMobility,
    OverheadMobility,
    PecsMobility;

    companion object {
        val allValues: List<DemoExercise> = values().toList()

        /** Exercises shown in 2D session, matching the iOS demo list. */
        val ios2DExercises: List<DemoExercise> = listOf(
            StandingSideBendRight,
            StandingSideBendLeft,
            JeffersonCurl,
            SquatRegular,
            SquatRegularOverheadStatic,
            PlankHighStatic,
            StandingKneeRaiseRight,
            StandingKneeRaiseLeft,
            AnkleMobilityLeft,
            AnkleMobilityRight
        )
    }
}
